<?php $user = new UserSession(); ?>
<?php if (empty($_SESSION)):?>
	<div class="signup">
			<fieldset class="info_sign_up login back">
				<legend>SIGN UP</legend>
					<form action="<?= $requestUrl; ?>/users/signup" method="post" enctype="multipart/form-data">
						<input type="hidden" name="checkup" value="signup">
						<input type="email" name="email" placeholder="your email">
						<input type="password" name="password" placeholder="your password">
						<input type="text" name="name" placeholder="your full name">
						<input type="text" name="adress" placeholder="your adress">
						<input type="text" name="phone" placeholder="your phone number">
						<input type="text" name="zip" placeholder="your zip">
						<input type="file" name="image" value="your profil">
						<input type="submit" name="submit" id="but_sign_up">
						<a class="button_switch">you already have an account</a>
					</form>
			</fieldset>
				<form class="info_sign_up front" action="<?= $requestUrl; ?>/users/signup" method="post" enctype="multipart/form-data">
					<fieldset class="login">
						<legend>LOG IN </legend>
						<input type="hidden" name="checkup" value="login">
						<input type="email" name="email" placeholder="your email">
						<input type="password" name="password" placeholder="your password">
						<input type="submit" name="submit" id="but_sign_up">
						<a class="button_switch">you're not a member yet</a>
					</fieldset>
				</form>
		</div>
<?php endif ; ?>
<?php 

	if (!empty($_SESSION)) 
		{
			$url = "#";
            $http = new Http();
            $red  = $http->redirectTo($url);
		}

?>